export const FETCH_TOP_TRACKS = 'topTracks/FETCH_TOP_TRACKS';

export const FETCH_ARTIST = 'artist/FETCH_ARTIST';
export const SET_ARTIST_IMAGE = 'artist/SET_ARTIST_IMAGE';

export const FETCH_SEARCHED_TRACK = 'trackSearch/FETCH_SEARCHED_TRACK';
export const CLEAR_TRACK_PREVIEW = 'trackSearch/CLEAR_TRACK_PREVIEW';
export const SET_SEARCH_ERROR = 'trackSearch/SET_SEARCH_ERROR';
export const CLEAR_SEARCH_ERROR = 'trackSearch/CLEAR_SEARCH_ERROR';
export const SET_INPUT_ERROR = 'trackSearch/SET_INPUT_ERROR';
export const CLEAR_INPUT_ERROR = 'trackSearch/CLEAR_INPUT_ERROR';

export const SET_REQUEST_TOP_TRACKS_ERROR = 'app/SET_REQUEST_TOP_TRACKS_ERROR';
export const SET_REQUEST_SEARCH_TRACK_ERROR
  = 'app/SET_REQUEST_SEARCH_TRACK_ERROR';
export const SET_REQUEST_ARTIST_ERROR = 'app/SET_REQUEST_ARTIST_ERROR';

export const PAGE_NAMES = {
  TOP_TRACKS: 'TOP_TRACK_PAGE',
  SEARCH_TRACK: 'SEARCH_TRACK_PAGE',
  ARTIST: 'ARTIST_PAGE',
};
